--- #YAML:1.0
name:                File-ANVL
version:             0.20
abstract:            routines to support A Name Value Language
license:             BSD
author:              
    - John A. Kunze <jak@ucop.edu>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Text::Wrap:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
