--- #YAML:1.0
name:               File-ANVL
version:            0.14
abstract:           routines to support A Name Value Language, version 0.1
author:
    - John A. Kunze <jak@ucop.edu>
license:            Apache2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Text::Wrap:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
